name: katas
version: 0.1.0.0
author: Attila Domokos <adomokos@gmail.com>
maintainer: adomokos@gmail.com
copyright: 2018 Attila Domokos
category: Console App
homepage: https://github.com/adomokos/hashmir#readme

# ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5

# library:
  # source-dirs: src/

executables:
  katas-exe:
    source-dirs: app/
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N

tests:
  katas-test:
    source-dirs: test/
    main: Spec.hs
    dependencies:
      - hspec == 2.*
      - containers
      - bytestring
      - mtl
